### ISSUE TITLE
gbif.bib not created correctly

### ISSUE THREAD

**Issue by szylinski-sa** [Acanthiza/envImport#6]
Had some trouble on the report end reading the gbif.bib created by get_gbif. Pretty sure I tracked it to an unneeded extra "}"

Line 214 of get_gbif.R
`ref[1] <- paste0("@misc{gbif}")`
`ref[1] <- paste0("@misc{gbif,")` - remove trailing `}` and replace with `,`

If I'm added as a contributor I can handle it.

**Comment by Acanthiza** [comment]
Go for it!

**Comment by szylinski-sa** [comment]
Fixed with 5537a66
