### ISSUE TITLE
get_gbif error

### ISSUE THREAD

**Issue by ZacPentecost** [Acanthiza/envImport#9]
@Acanthiza  Running get_gbif with the new changes to envOcc occurs with the following error. Wondering if anyone else is coming across this error or if its just me?

Error occurs after running this part of get_gbif.

```
gbif_download <- rgbif::occ_download(
                    rgbif::pred_and(rgbif::pred("HAS_GEOSPATIAL_ISSUE"
                                                , FALSE
                                                )
                                    , rgbif::pred("HAS_COORDINATE"
                                                , TRUE
                                                )
                                    , rgbif::pred_not(rgbif::pred_in("BASIS_OF_RECORD"
                                                                    , c("FOSSIL_SPECIMEN"
                                                                        , "LIVING_SPECIMEN"
                                                                        )
                                                                    )
                                                    )
                                    , ...
                                    )
                    , rgbif::pred_within(aoiWKT)
                    )
```
                    
```           
Error in preds_factory("and")(.list, ...) :
  1 or more inputs is not of class 'occ_predicate'; see docs
  
```
  
I think this might be linked to the way additional args are passed through the function get_data now and some of the args being passed to occ_download are not accepted but im not 100% sure. Investigating now but just wanted to flag in case you knew a quick sols

Thanks

**Comment by ZacPentecost** [comment]
oh wait I see this might be similar to #7

**Comment by Acanthiza** [comment]
Yes, you've exposed my hacky response to #7 which was to attempt just passing the dots as well. Does it work for you via get_gbif() directly?

**Comment by ZacPentecost** [comment]
If I'm interpreting you correctly, yes it does work running get_gbif() directly.

**Comment by Acanthiza** [comment]
Ok, ta. I'll see if I can get get_data working with get_gbif.

**Comment by ZacPentecost** [comment]
Thank you ... I've tried a couple of ways but to no success so far

**Comment by Acanthiza** [comment]
So `get_data` should be working with data_name = "gbif" (though note the changed arguments to `get_gbif`, particularly 'predicates'). But in order to combine with other data_names, still need to reconcile the schema for arrow::open_dataset().

**Comment by ZacPentecost** [comment]
Genius - tested and all looks good on my end. Thank you, Nigel.
